parser: '@typescript-eslint/parser'
plugins:
  - 'jest'
  - 'prettier'
  - '@typescript-eslint'
extends:
  - 'prettier'
  - 'react-app'
  - 'react-app/jest'
  - 'plugin:jest/recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  'prettier/prettier': 'warn'
